// ********RoostGPT********
/*
Test generated by RoostGPT for test NodeTesting using AI Type Open AI and AI Model gpt-4-1106-preview

ROOST_METHOD_HASH=ad824a76d3
ROOST_METHOD_SIG_HASH=79fbc45efd


*/

// ********RoostGPT********
import request from 'supertest';
import path from 'path';
import express from 'express';

// Assuming app is your Express app
const app = express();

app.use(express.static(path.join(path.resolve(), '../frontend', 'build')));

// We begin writing our test suite
describe('GET /*', () => {
  test('It should respond with the index.html file', async () => {
    const response = await request(app).get('/');
    expect(response.statusCode).toBe(200);
    expect(response.type).toBe('text/html');
  });

  test('It should respond with index.html for non-existing paths', async () => {
    const response = await request(app).get('/non-existing-path');
    expect(response.statusCode).toBe(200);
    expect(response.type).toBe('text/html');
  });

  // Add more tests here if needed
});

