// ********RoostGPT********
/*
Test generated by RoostGPT for test NodeTesting using AI Type Open AI and AI Model gpt-4-1106-preview

ROOST_METHOD_HASH=ad824a76d3
ROOST_METHOD_SIG_HASH=79fbc45efd


*/

// ********RoostGPT********
{
    "version": 2,
    "tasks": [
        {
            "name": "serve-files",
            "plugin": "npm",
            "option": "default",
            "packageJsonPath": "./backend/package.json"
        },
        {
            "name": "install-jest",
            "plugin": "npm",
            "runScript": "install",
            "packageJsonPath": "./backend/package.json",
            "dependencies": {
                "jest": "latest"
            }
        },
        {
            "name": "run-jest-tests",
            "plugin": "npm",
            "runScript": "test",
            "packageJsonPath": "./backend/package.json"
        }
    ],
    "env": {
        "CI": true
    }
}

