// ********RoostGPT********
/*
Test generated by RoostGPT for test NodeMochaTest using AI Type Open AI and AI Model gpt-4-1106-preview


ROOST_TEST_HASH=57665a017e

*/

// ********RoostGPT********
// jest.config.js
module.exports = {
  // Add any settings here to configure Jest
  testEnvironment: 'node',
};

// Access-Control-Allow-Origin.test.js
const express = require('express');
const request = require('supertest');

// This utility function mocks the app creation process which includes the middleware
function createServer() {
    const app = express();
    app.use((req, res, next) => {
        res.header('Access-Control-Allow-Origin', '*');
        res.header('Access-Control-Allow-Headers', '*');
        next();
    });
    app.get('/', (req, res) => { 
        res.status(200).send('OK'); 
    });
    return app;
}

// Test suite for Access-Control-Allow-Origin
describe('Access-Control-Allow-Origin Middleware', () => {
    let app;

    // Setup application before each test
    beforeAll(() => {
        app = createServer();
    });

    test('It should set the Access-Control-Allow-Origin header to *', async () => {
        const response = await request(app).get('/');
        expect(response.headers['access-control-allow-origin']).toBe('*');
    });

    test('It should set the Access-Control-Allow-Headers header to *', async () => {
        const response = await request(app).get('/');
        expect(response.headers['access-control-allow-headers']).toBe('*');
    });
});

